# Generated by Django 5.2.8 on 2025-11-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(max_length=100)),
                ('courseCode', models.CharField(max_length=100)),
                ('prequisite', models.BooleanField()),
                ('schedule', models.TimeField()),
                ('maxStudents', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentID', models.CharField(max_length=100)),
                ('studentID', models.CharField(max_length=100)),
                ('courseID', models.CharField(max_length=100)),
                ('enrollmentDL', models.DateField()),
                ('grade', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructorID', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('courseTeaching', models.CharField(max_length=100)),
                ('hiredDate', models.DateField()),
                ('officeLocation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentID', models.CharField(max_length=100)),
                ('studentID', models.CharField(max_length=100)),
                ('transactID', models.CharField(max_length=100)),
                ('paymentStatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phoneNo', models.IntegerField()),
                ('address', models.TextField(max_length=100)),
                ('enrollmentYr', models.CharField(max_length=100)),
            ],
        ),
    ]
