# Generated by Django 5.2.8 on 2025-11-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentmodel',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
