# Generated by Django 5.2.8 on 2025-11-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_enrollmentmodel_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='phoneNo',
            field=models.CharField(max_length=100),
        ),
    ]
